[project]
name = "auth-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "luishbarros", email = "luishrbr@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi>=0.141.1",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.51",
]

[project.scripts]
auth-service = "auth_service:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
