from typing import Protocol
from datetime import datetime

class CacheRepository(Protocol):
    async def set(self, key: str, value: str, expires_at: datetime) -> None: ...
    async def get(self, key: str) -> str | None: ...
    async def delete(self, key: str) -> None: ...
    async def publish(self, key: str, value: str) -> None: ...